/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jaktodziala;

import com.aspose.pdf.Document;

import javax.swing.JOptionPane;

/**
 *
 * @author marci
 */
public class UzupelniaczOfertaStron extends javax.swing.JFrame {

    /**
     * Creates new form UzupelniaczOfertaStron
     */
    public UzupelniaczOfertaStron() {
        initComponents();
               this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NazwaText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CenaSklepText = new javax.swing.JTextField();
        CenaStronaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Stworz = new javax.swing.JButton();
        AutorText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DataText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GeneratorOfert-Strony");

        NazwaText.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        NazwaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazwaTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel1.setText("Nazwa Firmy:");

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel2.setText("Cena Sklepu:");

        CenaSklepText.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        CenaSklepText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaSklepTextActionPerformed(evt);
            }
        });

        CenaStronaText.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        CenaStronaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaStronaTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel3.setText("Cena Strony:");

        Stworz.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        Stworz.setText("Stwórz Oferte");
        Stworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StworzActionPerformed(evt);
            }
        });

        AutorText.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        AutorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel4.setText("Autor Oferty:");

        DataText.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        DataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel5.setText("Data Oferty:");

        jLabel9.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel9.setText("Mirit- oferta Strona i Sklep");
        jLabel9.setToolTipText("");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(209, Short.MAX_VALUE)
                                .addComponent(Stworz))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(117, 117, 117)))
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CenaStronaText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CenaSklepText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AutorText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DataText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CenaStronaText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CenaSklepText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutorText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Stworz)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazwaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazwaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NazwaTextActionPerformed

    private void CenaSklepTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenaSklepTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CenaSklepTextActionPerformed

    private void CenaStronaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenaStronaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CenaStronaTextActionPerformed

    private void StworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StworzActionPerformed
     
         String nazwa = NazwaText.getText();
        String cenaStrona = CenaStronaText.getText();
        String cenaSklep = CenaSklepText.getText();
        String autor = AutorText.getText();
        String data = DataText.getText();
        
              if(NazwaText.getText().equalsIgnoreCase("")||CenaStronaText.getText().equalsIgnoreCase("")||
                CenaSklepText.getText().equalsIgnoreCase("")
                ||AutorText.getText().equalsIgnoreCase("")
                ||DataText.getText().equalsIgnoreCase("")
                
                )
        {
               JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie pola zanim stworzysz Oferte"); 
        }
              else
              {
        Document pdfDocument = new Document("ofertaSklep.pdf");
        MetodyWczytujaceOfertyStrony.NazwaFirmy(pdfDocument, nazwa);
        MetodyWczytujaceOfertyStrony.CenaStrony(pdfDocument, cenaStrona);
        MetodyWczytujaceOfertyStrony.CenaSklepu(pdfDocument, cenaSklep);
        MetodyWczytujaceOfertyStrony.DataOferty(pdfDocument, data);
        MetodyWczytujaceOfertyStrony.AutorOferty(pdfDocument, autor);
        
        pdfDocument.save("./OfertyStronInternetowych/"+MetodyWczytujaceOfertyStrony.nazwaFirmy+"Oferta.pdf");
        JOptionPane.showMessageDialog(null, "Oferta została Stworzona");
              }
    }//GEN-LAST:event_StworzActionPerformed

    private void AutorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorTextActionPerformed

    private void DataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UzupelniaczOfertaStron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UzupelniaczOfertaStron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UzupelniaczOfertaStron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UzupelniaczOfertaStron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UzupelniaczOfertaStron().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutorText;
    private javax.swing.JTextField CenaSklepText;
    private javax.swing.JTextField CenaStronaText;
    private javax.swing.JTextField DataText;
    private javax.swing.JTextField NazwaText;
    private javax.swing.JButton Stworz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
